### ISSUE TITLE
getSRAfile: argument is of length zero

### ISSUE THREAD

**Issue by Npbs8691** [seandavi/SRAdb#25]
getSRAfile( in_acc = c("SRR2033366", "SRR2033446"), 
  sra_con = sra_con,
  destDir = getwd(), 
  fileType = 'sra', 
  srcType = 'ftp', 
  makeDirectory = FALSE,
  method = 'curl',
  ascpCMD = NULL)

Error in if (is.na(sra_acc$run[i])) { : argument is of length zero

**Comment by hank00000** [comment]
Did you find an answer? I am having the same problem.

**Comment by Npbs8691** [comment]
Nope. I didn't.

**Comment by thanhle7** [comment]
This problem has been there for a long time but no solution.

**Comment by thanhle7** [comment]
Looks like the problem is because of listSRAfile in which, for some reasons; sqlLite DB not updated properly for example, sra_acc got empty. The for loop then runs on 1:0, making the iterations of 1, 0; and producing problem.
`for( i in 1:nrow(sra_acc) ) {
`...
I tried to dev the new listSRAfile then the problem resolved.

**Comment by ChantKatrjian** [comment]
@thanhle7 How did you solve this issue? Can you share your modification?
