### ISSUE TITLE
getFASTQinfo fails - no such table: fastq

### ISSUE THREAD

**Issue by bkamapantula** [seandavi/SRAdb#6]
Hi,

It seems that getFASTQinfo() fails. I've tested this in R using the [man page, pdf](http://www.bioconductor.org/packages/release/bioc/manuals/SRAdb/man/SRAdb.pdf) 

`getFASTQinfo(c("SRR020520"), sra_con, 'ftp')`
Error below:

Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: fastq
Calls: getInfo ... .local -> sqliteGetQuery -> sqliteSendQuery -> .Call
Execution halted

Has anyone noticed this?

thanks,

**Comment by ddomman** [comment]
I've also noticed this. For me it seems that anything to do with fastq files doesn't work.  
```R
getFASTQfile(testlist,srcType = 'ftp', sra_con = sra_con)
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: fastq

listSRAfile (in_acc = accessions, sra_con, fileType='fastq', srcType = 'ftp')
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: fastq
```
Help on this issue would be greatly appreciated.

Thanks

**Comment by eavincent** [comment]
See my post on getSRAinfo()

**Comment by eavincent** [comment]
To solve the listSRAfile() problem, I found it was actually an issue with the previous step,
```
sqlfile<<-getSRAdbFile()
trying URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'
Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) : 
  cannot open URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'
```
I did not find a direct solution -- I read somewhere, maybe in another issue here, that the problem is the dropbox link requires a redirect that the download.file() function cannot handle but that wget() may be able to.  The work-around I used was to go to the URL directly in my web browser, which automatically downloads the zipped file, and transfer the file to my working directory.  I then continued with the getSRAdbFile() source code beginning at gunzip() (requires R.utils package).

Once getSRAdbFile() is working correctly listSRAfile() will work because getSRAdbFile() provided the necessary table (SRAmetadb.sqlite)

**Comment by ShixiangWang** [comment]
@eavincent my error is 
```
Error in rsqlite_send_query(conn@ptr, statement) : no such table: sra
```
when use `getFASTQfile("SRR921344", sra_con, destDir = getwd(), srcType = 'ftp', ascpCMD = NULL )`. What is the difference between `sra` and `fastq` table? Can I fix the error by `getSRAdbFile()`？

**Comment by seandavi** [comment]
@ShixiangWang, yes, you need to download the SQLite file using getSRAdbFile() before the package can be used for querying. If you have problems, could you post a question to https://support.bioconductor.org/ and tag the question with `SRAdb`?
